version: "3"

services:
  docmost:
    # image: docmost/docmost:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    environment:
      # APP_URL: "http://localhost:3001"
      APP_SECRET: "efccabc0d32ba9433b5d4819a0fca28c938417a0dc88ba94a1835e1e47362d57"
      DATABASE_URL: "postgresql://docmost:digilab@db:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
      VITE_GITHUB_TOKEN: "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"
    ports:
      - "3001:3000"
    restart: unless-stopped
    volumes:
      - ./data/docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: digilab
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - ./data/db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  # docmost:
  db_data:
  redis_data:

# admin@admin.com
# admin
